
-- Use debug lines to draw a floor grid.

local draw = require "debug-draw"
local vec3 = vmath.vector3

go.property("spacing", 1)
go.property("count", 15)
go.property("color", vmath.vector4(0.35, 0.65, 1, 1))

function init(self)
	self.lines = {}
	local size = (self.count - 1) * self.spacing
	local z1, z2 = -size/2, size/2
	local ox = -(self.count-1)/2 * self.spacing
	for i=0,self.count-1 do
		local x = ox + i*self.spacing
		table.insert(self.lines, { vec3(x, 0, z1), vec3(x, 0, z2) })

		table.insert(self.lines, { vec3(z1, 0, x), vec3(z2, 0, x) })
	end
end

function update(self, dt)
	for i,l in ipairs(self.lines) do
		draw.ray(l[1], l[2], self.color)
	end
end
