
local TURN_UP = hash("turn up")
local TURN_DOWN = hash("turn down")
local TURN_LEFT = hash("turn left")
local TURN_RIGHT = hash("turn right")

local speed = 2

function init(self)
	msg.post(".", "acquire_input_focus")
	self.dt = 0
end

function update(self, dt)
	self.dt = dt
end

local function add_rot(x, y)
	local rot = go.get_rotation()
	if x then  rot = rot * vmath.quat_rotation_y(x)  end
	if y then  rot = rot * vmath.quat_rotation_x(y)  end
	go.set_rotation(rot)
end

function on_input(self, action_id, action)
	if action_id == TURN_UP then
		add_rot(nil, speed * self.dt)
	elseif action_id == TURN_DOWN then
		add_rot(nil, -speed * self.dt)
	elseif action_id == TURN_LEFT then
		add_rot(speed * self.dt)
	elseif action_id == TURN_RIGHT then
		add_rot(-speed * self.dt)
	end
end
